SELECT TOP 2 CITY, LEN(CITY)
FROM STATION
WHERE LEN(CITY) = (SELECT MAX(LEN(CITY))  FROM STATION )
OR    LEN(CITY) = (SELECT MIN(LEN(CITY))  FROM STATION )
ORDER BY LEN(CITY) DESC , CITY ASC;

--------------------------------------------------------------
(SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC
LIMIT 1)

UNION

(SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1);

------------------------------------------------------------------------
WITH TEMP AS
(SELECT CITY, LEN(CITY),
				row_number() OVER(ORDER BY LEN(CITY) DESC, CITY DESC) AS rn
FROM STATION)

SELECT CITY, LEN(CITY) FROM TEMP
WHERE rn = 1 or rn = (SELECT MAX(rn) FROM TEMP);
